//
//  OnboardingImageResources.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

/// ImageResource is generated by the DeveloperTool. Currently is not possible to define the Asset Symbols public.
/// The generated `struct ImageResource` is internal to the package and not possible to access from another target.
/// `OnboardingImageResource`is a minimal UI-Framework agnostic thin wrapper that carries the
/// only two things needed to resolve an asset — its `name` and the `bundle`
/// Fore more info see:
/// - [Swift Forum](https://forums.swift.org/t/xcode15-generated-imageresource-with-public-access/67293)
/// - [Developer Forum](https://developer.apple.com/forums/thread/756954)
public struct OnboardingImageResource: Hashable {
    public let name: String
    public let bundle: Bundle
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

public extension Image {

    /// Resolves an ``OnboardingImageResource`` into a SwiftUI `Image` at the UI layer.
    init(_ resource: OnboardingImageResource) {
        self.init(ImageResource(name: resource.name, bundle: resource.bundle))
    }

}

/// Namespaced catalog of onboarding image assets, exposed as ``OnboardingImageResource``
/// values so they can be referenced from UI-framework-agnostic content models.
public enum OnboardingImageResources {

    public enum DownloadReason {
        public static let search = OnboardingImageResource(name: "Rebranding/Search", bundle: .module)
        public static let aiChat = OnboardingImageResource(name: "Rebranding/AI-Chat", bundle: .module)
        public static let noAI = OnboardingImageResource(name: "Rebranding/No-AI", bundle: .module)
        public static let blockAds = OnboardingImageResource(name: "Rebranding/Block-Ads", bundle: .module)
    }

}
