//
//  RoseColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

#if os(macOS)

/// Autogenerated from [Figma](https://www.figma.com/design/lowzSNK3XysASQ1urGCZFp/Browser-Color-Themes?node-id=504-17677&m=dev)
struct RoseColorPalette: SharedColorPaletteDefinition {
    static let accentAltContentPrimary = DynamicColor(lightHex: 0x660047, darkHex: 0xfffafe)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x660047, lightOpacityHex: 0xb2, darkHex: 0xfffafe, darkOpacityHex: 0xb2)
    static let accentAltContentTertiary = DynamicColor(lightHex: 0x660047, lightOpacityHex: 0x7f, darkHex: 0xfffafe, darkOpacityHex: 0x7f)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0xfa7ddd, lightOpacityHex: 0x33, darkHex: 0xfa7ddd, darkOpacityHex: 0x33)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0xfa7ddd, lightOpacityHex: 0x1e, darkHex: 0xfa7ddd, darkOpacityHex: 0x1e)
    static let accentAltPrimary = DynamicColor(lightHex: 0xfbb0ea, darkHex: 0xc1008e)
    static let accentAltSecondary = DynamicColor(lightHex: 0xfa7ddd, darkHex: 0xa30074)
    static let accentAltTertiary = DynamicColor(lightHex: 0xf249c5, darkHex: 0x84005c)
    static let accentAltTextPrimary = DynamicColor(lightHex: 0xa30074, darkHex: 0xffa8ea)
    static let accentAltTextSecondary = DynamicColor(lightHex: 0x84005c, darkHex: 0xfa7ddd)
    static let accentAltTextTertiary = DynamicColor(lightHex: 0x660047, darkHex: 0xf249c5)
    static let accentBrandContentPrimary = DynamicColor(lightHex: 0x660047, darkHex: 0x660047)
    static let accentBrandContentSecondary = DynamicColor(lightHex: 0x660047, lightOpacityHex: 0xb2, darkHex: 0x660047, darkOpacityHex: 0xb2)
    static let accentBrandContentTertiary = DynamicColor(lightHex: 0x660047, lightOpacityHex: 0x7f, darkHex: 0x660047, darkOpacityHex: 0x7f)
    static let accentBrandGlowPrimary = DynamicColor(lightHex: 0xfa7ddd, lightOpacityHex: 0x33, darkHex: 0xfa7ddd, darkOpacityHex: 0x33)
    static let accentBrandGlowSecondary = DynamicColor(lightHex: 0xfa7ddd, lightOpacityHex: 0x1e, darkHex: 0xfa7ddd, darkOpacityHex: 0x1e)
    static let accentBrandPrimary = DynamicColor(lightHex: 0xfbb0ea, darkHex: 0xfbb0ea)
    static let accentBrandSecondary = DynamicColor(lightHex: 0xfa7ddd, darkHex: 0xfa7ddd)
    static let accentBrandTertiary = DynamicColor(lightHex: 0xf249c5, darkHex: 0xf249c5)
    static let accentBrandTextPrimary = DynamicColor(lightHex: 0xa30074, darkHex: 0xa30074)
    static let accentBrandTextSecondary = DynamicColor(lightHex: 0x84005c, darkHex: 0x84005c)
    static let accentBrandTextTertiary = DynamicColor(lightHex: 0x660047, darkHex: 0x660047)
    static let accentContentPrimary = DynamicColor(lightHex: 0xfffafe, darkHex: 0x30031e)
    static let accentContentSecondary = DynamicColor(lightHex: 0xfffafe, lightOpacityHex: 0xb2, darkHex: 0x30031e, darkOpacityHex: 0xb2)
    static let accentContentTertiary = DynamicColor(lightHex: 0xfffafe, lightOpacityHex: 0x7f, darkHex: 0x30031e, darkOpacityHex: 0x7f)
    static let accentFireContentPrimary = DynamicColor(lightHex: 0xffffff, darkHex: 0xffffff)
    static let accentFireContentSecondary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0xb2, darkHex: 0xffffff, darkOpacityHex: 0xb2)
    static let accentFireContentTertiary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x7f, darkHex: 0xffffff, darkOpacityHex: 0x7f)
    static let accentFireGlowPrimary = DynamicColor(lightHex: 0xf05f2b, lightOpacityHex: 0x33, darkHex: 0xff8d5c, darkOpacityHex: 0x33)
    static let accentFireGlowSecondary = DynamicColor(lightHex: 0xf05f2b, lightOpacityHex: 0x1e, darkHex: 0xff8d5c, darkOpacityHex: 0x1e)
    static let accentFirePrimary = DynamicColor(lightHex: 0xf05f2a, darkHex: 0xff8c5b)
    static let accentFireSecondary = DynamicColor(lightHex: 0xcc3b0a, darkHex: 0xf05f2a)
    static let accentFireTertiary = DynamicColor(lightHex: 0x9e2b08, darkHex: 0xcc3b0a)
    static let accentFireTextPrimary = DynamicColor(lightHex: 0xf05f2a, darkHex: 0xff8c5b)
    static let accentFireTextSecondary = DynamicColor(lightHex: 0xcc3b0a, darkHex: 0xf05f2a)
    static let accentFireTextTertiary = DynamicColor(lightHex: 0x9e2b08, darkHex: 0xcc3b0a)
    static let accentGlowPrimary = DynamicColor(lightHex: 0xd90090, lightOpacityHex: 0x33, darkHex: 0xfa7ddd, darkOpacityHex: 0x33)
    static let accentGlowSecondary = DynamicColor(lightHex: 0xd90090, lightOpacityHex: 0x1e, darkHex: 0xfa7ddd, darkOpacityHex: 0x1e)
    static let accentPrimary = DynamicColor(lightHex: 0xc1008e, darkHex: 0xfa7ddd)
    static let accentQuaternary = DynamicColor(lightHex: 0x660047, darkHex: 0xd91ba0)
    static let accentSecondary = DynamicColor(lightHex: 0xa30074, darkHex: 0xf249c5)
    static let accentTertiary = DynamicColor(lightHex: 0x84005c, darkHex: 0xe52eae)
    static let accentTextPrimary = DynamicColor(lightHex: 0xa30074, darkHex: 0xffa8ea)
    static let accentTextSecondary = DynamicColor(lightHex: 0x84005c, darkHex: 0xfa7ddd)
    static let accentTextTertiary = DynamicColor(lightHex: 0x660047, darkHex: 0xf249c5)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x0f, darkHex: 0xfffafe, darkOpacityHex: 0x16)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x16, darkHex: 0xfffafe, darkOpacityHex: 0x1e)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x1e, darkHex: 0xfffafe, darkOpacityHex: 0x28)
    static let containerFillPrimary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x05, darkHex: 0xfffafe, darkOpacityHex: 0x07)
    static let containerFillSecondary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x0a, darkHex: 0xfffafe, darkOpacityHex: 0x0f)
    static let containerFillTertiary = DynamicColor(lightHex: 0x2b081c, lightOpacityHex: 0x0f, darkHex: 0xfffafe, darkOpacityHex: 0x16)
    static let controlsBorderPrimary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x51, darkHex: 0xfc9ce6, darkOpacityHex: 0x7a)
    static let controlsBorderQuaternary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0xb7, darkHex: 0xfc9ce6, darkOpacityHex: 0xcc)
    static let controlsBorderSecondary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x8e, darkHex: 0xfc9ce6, darkOpacityHex: 0xa3)
    static let controlsBorderTertiary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0xa3, darkHex: 0xfc9ce6, darkOpacityHex: 0xb7)
    static let controlsFillPrimary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x16, darkHex: 0xfc9ce6, darkOpacityHex: 0x1e)
    static let controlsFillSecondary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x1e, darkHex: 0xfc9ce6, darkOpacityHex: 0x2d)
    static let controlsFillTertiary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x2d, darkHex: 0xfc9ce6, darkOpacityHex: 0x3d)
    static let controlsRaisedBackdrop = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x16, darkHex: 0xffffff, darkOpacityHex: 0x1e)
    static let controlsRaisedFillPrimary = DynamicColor(lightHex: 0xfffafe, darkHex: 0xfffafe, darkOpacityHex: 0x2d)
    static let controlsRaisedFillSecondary = DynamicColor(lightHex: 0xffffff, darkHex: 0xfffafe, darkOpacityHex: 0x2d)
    static let controlsRaisedFillTertiary = DynamicColor(lightHex: 0xffffff, darkHex: 0xfffafe, darkOpacityHex: 0x2d)
    static let controlsSubtleBorderPrimary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x1e, darkHex: 0xfc9ce6, darkOpacityHex: 0x1e)
    static let controlsSubtleBorderSecondary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x2d, darkHex: 0xfc9ce6, darkOpacityHex: 0x2d)
    static let controlsSubtleBorderTertiary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x5b, darkHex: 0xfc9ce6, darkOpacityHex: 0x5b)
    static let controlsSubtleFillPrimary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x07, darkHex: 0xfc9ce6, darkOpacityHex: 0x1e)
    static let controlsSubtleFillSecondary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x14, darkHex: 0xfc9ce6, darkOpacityHex: 0x2d)
    static let controlsSubtleFillTertiary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x19, darkHex: 0xfc9ce6, darkOpacityHex: 0x3d)
    static let destructiveContentPrimary = DynamicColor(lightHex: 0xffffff, darkHex: 0x000000)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0xe5, darkHex: 0x000000, darkOpacityHex: 0xe5)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xffffff, lightOpacityHex: 0x99, darkHex: 0x000000, darkOpacityHex: 0x99)
    static let destructiveGlowPrimary = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x33)
    static let destructiveGlowSecondary = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x1e)
    static let destructivePrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTertiary = DynamicColor(lightHex: 0xaa1826, darkHex: 0xaa1926)
    static let destructiveTextPrimary = DynamicColor(lightHex: 0xee1025, darkHex: 0xee1025)
    static let destructiveTextSecondary = DynamicColor(lightHex: 0xd11527, darkHex: 0xd11527)
    static let destructiveTextTertiary = DynamicColor(lightHex: 0xaa1926, darkHex: 0xaa1926)
    static let highlightPrimary = DynamicColor(lightHex: 0xfffafe, lightOpacityHex: 0x3d, darkHex: 0xfffafe, darkOpacityHex: 0x1e)
    static let iconsPrimary = DynamicColor(lightHex: 0x30021e, lightOpacityHex: 0xd6, darkHex: 0xfffafe, darkOpacityHex: 0xc6)
    static let iconsSecondary = DynamicColor(lightHex: 0x30031e, lightOpacityHex: 0xa8, darkHex: 0xfffafe, darkOpacityHex: 0xa8)
    static let iconsTertiary = DynamicColor(lightHex: 0x30031e, lightOpacityHex: 0x5b, darkHex: 0xfffafe, darkOpacityHex: 0x5b)
    static let inputActive = DynamicColor(lightHex: 0xfffafe, darkHex: 0x72265e)
    static let inputResting = DynamicColor(lightHex: 0xf3cce9, darkHex: 0x72265e)
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x0c, darkHex: 0x000000, darkOpacityHex: 0x28)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x14, darkHex: 0x000000, darkOpacityHex: 0x3d)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacityHex: 0x28, darkHex: 0x000000, darkOpacityHex: 0x51)
    static let statusGray = DynamicColor(lightHex: 0xaaaaaa, darkHex: 0xaaaaaa)
    static let statusGreen = DynamicColor(lightHex: 0x21c000, darkHex: 0x21c000)
    static let statusRed = DynamicColor(lightHex: 0xea0f2c, darkHex: 0xea0f2c)
    static let statusWarningContentPrimary = DynamicColor(lightHex: 0x191101, darkHex: 0x191101)
    static let statusWarningFillPrimary = DynamicColor(lightHex: 0xffe699, lightOpacityHex: 0x51, darkHex: 0xffb200, darkOpacityHex: 0x1e)
    static let statusWarningPrimary = DynamicColor(lightHex: 0xffcc00, darkHex: 0xffcc00)
    static let statusYellow = DynamicColor(lightHex: 0xffcc00, darkHex: 0xffcc00)
    static let surfaceBackdrop = DynamicColor(lightHex: 0xee9fd9, darkHex: 0x2d0525)
    static let surfaceCanvas = DynamicColor(lightHex: 0xfcf3fa, darkHex: 0x511442)
    static let surfaceContrast = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0xf4, darkHex: 0xfa7ddd, darkOpacityHex: 0xf4)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x1e, darkHex: 0xfa7ddd, darkOpacityHex: 0x28)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x33, darkHex: 0xfa7ddd, darkOpacityHex: 0x3d)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0xa30075, lightOpacityHex: 0x51, darkHex: 0xfa7ddd, darkOpacityHex: 0x51)
    static let surfacePrimary = DynamicColor(lightHex: 0xf6e4f1, darkHex: 0x5b194b)
    static let surfaceSecondary = DynamicColor(lightHex: 0xfaeef8, darkHex: 0x692055)
    static let surfaceTertiary = DynamicColor(lightHex: 0xfffafe, darkHex: 0x72265e)
    static let textPrimary = DynamicColor(lightHex: 0x30021e, lightOpacityHex: 0xf4, darkHex: 0xfffafe, darkOpacityHex: 0xf4)
    static let textSecondary = DynamicColor(lightHex: 0x30031e, lightOpacityHex: 0x99, darkHex: 0xfffafe, darkOpacityHex: 0xa8)
    static let textTertiary = DynamicColor(lightHex: 0x30031e, lightOpacityHex: 0x5b, darkHex: 0xfffafe, darkOpacityHex: 0x5b)
    static let toneShadePrimary = DynamicColor(lightHex: 0x1a0511, lightOpacityHex: 0x0f, darkHex: 0x1c0112, darkOpacityHex: 0x28)
    static let toneTintPrimary = DynamicColor(lightHex: 0xfffafe, lightOpacityHex: 0x7a, darkHex: 0xffeafa, darkOpacityHex: 0x0f)
    static let toneTintSecondary = DynamicColor(lightHex: 0xfffafe, lightOpacityHex: 0xd6, darkHex: 0xffeafa, darkOpacityHex: 0x1e)

    // MARK: - Inherited from FigmaColorPalette

    static let destructiveGlow = DynamicColor(lightHex: 0xee1025, lightOpacityHex: 0x33, darkHex: 0xee1025, darkOpacityHex: 0x33)

    // MARK: - Not Specialized

    static let alertGreen = DynamicColor(lightColor: .alertGreen, darkColor: .alertGreen)
    static let alertYellow = DynamicColor(lightColor: .alertYellow, darkColor: .alertYellow)
    static let shieldPrivacy = DynamicColor(lightColor: RebrandingColor.Lilypad.lilypad70, darkColor: RebrandingColor.Lilypad.lilypad50)

    static let buttonsWhite = DynamicColor(lightColor: .white, darkColor: .black)

    static let buttonsPrimaryDefault = DynamicColor(lightColor: .blue50, darkColor: .blue30)
    static let buttonsPrimaryPressed = DynamicColor(lightColor: .blue70, darkColor: .blue50)
    static let buttonsPrimaryDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsPrimaryText = DynamicColor(lightColor: .white, darkColor: .shade(0.84))
    static let buttonsPrimaryTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let buttonsSecondaryFillDefault = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillPressed = DynamicColor(lightColor: .shade(0.18), darkColor: .tint(0.3))
    static let buttonsSecondaryFillDisabled = DynamicColor(lightColor: .shade(0.06), darkColor: .tint(0.18))
    static let buttonsSecondaryFillText = DynamicColor(lightColor: .shade(0.84), darkColor: .white)
    static let buttonsSecondaryFillTextDisabled = DynamicColor(lightColor: .shade(0.36), darkColor: .tint(0.36))

    static let lines = DynamicColor(lightHex: 0x1F1F1F, lightOpacity: 0.09, darkHex: 0xF9F9F9, darkOpacity: 0.12)
}

#endif
