name: Shared - Assign GitHub Reviewer to Asana Task

on:
    pull_request:
        types: [review_requested]

jobs:

    create-asana-pr-subtask-if-needed:
        if: ${{ github.event.requested_reviewer && github.event.requested_reviewer.login != 'Copilot' && github.event.requested_reviewer.login != '' }}
        name: "Create the PR subtask in Asana"
        runs-on: ubuntu-latest

        steps:
        - name: Get Task ID
          id: get-task-id
          uses: duckduckgo/apple-toolbox/actions/asana-extract-task-id@main
          with:
            text: ${{ github.event.pull_request.body }}

        - name: Create or Update PR Subtask
          uses: duckduckgo/apple-toolbox/actions/asana-create-pr-subtask@main
          with:
            access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
            asana-task-id: ${{ steps.get-task-id.outputs.task-id }}
            github-reviewer-user: ${{ github.event.requested_reviewer.login }}
            github-pr-author-user: ${{ github.event.pull_request.user.login }}
            github-pr-author-type: ${{ github.event.pull_request.user.type }}
            github-token: ${{ secrets.APPLE_GH_RO_PAT }}
            asana-project-id: ${{ vars.APPLE_TEAM_CODE_REVIEWS_ASANA_PROJECT_ID }}
            asana-section-id: ${{ vars.APPLE_TEAM_CODE_REVIEWS_SECTION_ID }}
